---
title: "Air Quality"
output: html_document
date: "2026-01-19"
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(htmlwidgets)
library(data.table)

```

```{r}
vars = c("pm1", "pm25", "pm10", "NO", "NO2", "CO", "O3")

name_mapping <- c(
  "lismore" = "Lismore",
  "perth" = "Perth",
  "tennant" = "Tennant Creek"
)

latlong_mapping <- list(
  "lismore" = c(-28.8094, 153.2879),
  "perth" = c(-31.9514, 115.8617),
  "tennant" = c(-19.6459, 134.1910)
)

df <- readRDS("../Climate Data/air_quality_processed.rds")
df$date <- as.Date(df$date)

```


```{r}
library(ggplot2)

for (var in unique(df$variable)) {
  var_data <- df[df$variable == var, ]
  
  p <- ggplot(var_data, aes(x = date, y = value, color = location, group = location)) +
    geom_line(alpha = 0.5) +
    labs(title = paste0("Air Quality (", var, ")"),
         x = "Date", y = "Value", color = "Location") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_x_date(date_labels = "%Y-%m", date_breaks = "6 months")
  
  # Save as PNG
  file_name <- paste0("air_quality_", var, ".png")
  ggsave(filename = file_name, plot = p, width = 10, height = 6, dpi = 300)
}

```


