---
title: "Circular temperature"
output: html_document
date: "2026-01-16"
---
```{r}
library(ggplot2)
library(gganimate)
library(dplyr)

source("plot_utils.R")
source("parse_utils.R")
```


```{r}
location = "tennant" # options are: perth, tennant, lismore

name_mapping <- c(
  "lismore" = "Lismore",
  "perth" = "Perth",
  "tennant" = "Tennant Creek"
)
mapped_location <- name_mapping[location]
```


```{r}
data <- process_data_LP(location)
data
```


```{r}
# circular plot with temperature on the radial axis and time (day_of_year) on the angular axis
# all history, new years overlayed
plot <- plot_reveal(data, mapped_location)

# Create the animation and display it inline
nframes=length(unique(data$year))
anim <- animate(plot, nframes = nframes, fps = 10, width = 800, height = 800, renderer = gifski_renderer())
print(anim)

```

```{r}
anim_save(paste0("climate_temp_circular_",location,"1.gif"), animation = anim)
```



```{r}
# circular plot with temperature on the radial axis and time (degrees) on the angular axis
# all history at 50% transparency, takes longer to render
plot <- plot_shadow(data, mapped_location)

nframes=length(unique(data$year))
anim <- animate(plot, nframes = nframes, fps = 10, width = 800, height = 800, renderer = gifski_renderer())

print(anim)

```

```{r}
anim_save(paste0("climate_temp_circular_",location,"2.gif"), animation = anim)
```

```{r}
location = "lismore" # options are: perth, tennant, lismore

name_mapping <- c(
  "lismore" = "Lismore",
  "perth" = "Perth",
  "tennant" = "Tennant Creek"
)
mapped_location <- name_mapping[location]

data <- process_data_LP(location)
data

# circular plot with temperature on the radial axis and time (day_of_year) on the angular axis
# all history, new years overlayed
plot <- plot_reveal(data, mapped_location)

# Create the animation and display it inline
nframes=length(unique(data$year))
anim <- animate(plot, nframes = nframes, fps = 10, width = 800, height = 800, renderer = gifski_renderer())
print(anim)

```

```{r}
anim_save(paste0(location,"_maxtemp1.gif"), animation = anim)
```

```{r}
location = "perth" # options are: perth, tennant, lismore

name_mapping <- c(
  "lismore" = "Lismore",
  "perth" = "Perth",
  "tennant" = "Tennant Creek"
)
mapped_location <- name_mapping[location]

data <- process_data_LP(location)
data

# circular plot with temperature on the radial axis and time (day_of_year) on the angular axis
# all history, new years overlayed
plot <- plot_reveal(data, mapped_location)

# Create the animation and display it inline
nframes=length(unique(data$year))
anim <- animate(plot, nframes = nframes, fps = 10, width = 800, height = 800, renderer = gifski_renderer())
print(anim)
```

```{r}
anim_save(paste0(location,"_maxtemp1.gif"), animation = anim)
```

