---
title: "Mortality Risk due to climate changes"
output: html_document
date: "2026-01-22"
---

```{r}
#Import libraries
library(dplyr)
library(ggplot2)
library(readr)
library(treemapify)
library(splines)
```

```{r}
df <- read_csv("Mortality by Gender 2014-2018.csv")
head(df)

combined_plot <- df %>%
  group_by(Site, Gender) %>%
  summarise(Total_Deaths = sum(Deaths, na.rm = TRUE))

#Violin Plot — Gender-wise distribution by site
ggplot(df, aes(x = Gender, y = Deaths, fill = Gender)) +
  geom_violin(trim = FALSE) +
  facet_wrap(~ Site, scales = "free") +
  labs(title = "Violin Plot of Mortality by Gender and Site 2014-2018",
       x = "Gender", y = "Deaths") +
  theme_minimal()
```

```{r}
df <- read_csv("Mortality by Gender 2019-2023.csv")
attach(df)
head(df)

combined_plot <- df %>%
  group_by(Site, Gender) %>%
  summarise(Total_Deaths = sum(Deaths, na.rm = TRUE))

#Violin Plot — Gender-wise distribution by site
ggplot(df, aes(x = Gender, y = Deaths, fill = Gender)) +
  geom_violin(trim = FALSE) +
  facet_wrap(~ Site, scales = "free") +
  labs(title = "Violin Plot of Mortality by Gender and Site 2019-2023",
       x = "Gender", y = "Deaths") +
  theme_minimal()

```



```{r}
#Treemap
df <- read.csv("Mortality by Gender 2014-2018.csv",  fileEncoding = "latin1")

df_sum <- df %>% group_by(cause) %>% summarise(deaths = sum(Deaths))

ggplot(df,aes(area = Deaths, fill = cause, label = cause)) +
  geom_treemap() +
  geom_treemap_text(colour = "white", place = "centre", grow = TRUE) +
  labs(title = "Treemap of Causes of Death from 2014-2018",
       fill = "Cause") +
  theme_minimal()
```

```{r}
#Treemap
df <- read_csv("Mortality by Gender 2019-2023.csv")
df_sum <- df %>% group_by(cause) %>% summarise(deaths = sum(Deaths))

ggplot(df,aes(area = Deaths, fill = cause, label = cause)) +
  geom_treemap() +
  geom_treemap_text(colour = "white", place = "centre", grow = TRUE) +
  labs(title = "Treemap of Causes of Death from 2019-2023",
       fill = "Cause") +
  theme_minimal()
```

```{r}
#Lollipop Chart
df <- read_csv("Mortality by Gender 2014-2018.csv")

df <- df %>%
  mutate(course_abbrev = recode(cause,
                                "Coronary heart disease "= "CHD",
                                "Cerebrovascular disease "  = "CD",
                                "Chronic obstructive pulmonary disease (COPD) "= "COPD",
                                "Heart failure and complications  " = "HFC"))

ggplot(df, aes(x = course_abbrev, y = Deaths, color = Gender)) +
  geom_segment(aes(xend = course_abbrev, yend = 0), linewidth = 1) +
  geom_point(size = 4) +
  facet_wrap(~ Site) +
  labs(
    title = "Lollipop Chart of Death Counts from 2014 to 2018",
    x = "Cause of death (Abbreviation)",
    y = "Number of Deaths"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.title = element_blank()
  )


```
```{r}
df <- read_csv("Mortality by Gender 2019-2023.csv")

df <- df %>%
  mutate(course_abbrev = recode(cause,
                                "Coronary heart disease"= "CHD",
                                "Cerebrovascular disease"  = "CD",
                                "Chronic obstructive pulmonary disease (COPD)"= "COPD",
                                "Coronavirus disease 2019 (COVID-19)" = "COVID-19",
                                "Heart failure and complications and ill-defined heart disease" = "HFC"))

#Lollipop Chart
ggplot(df, aes(x = course_abbrev, y = Deaths, color = Gender)) +
  geom_segment(aes(xend = course_abbrev, yend = 0), linewidth = 1) +
  geom_point(size = 4) +
  facet_wrap(~ Site) +
  labs(
    title = "Lollipop Chart of Death Counts from 2019 to 2023",
    x = "Cause of death (Abbreviation)",
    y = "Number of Deaths"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.title = element_blank()
  )

```

